[2025-01-17 00:38:45,789] 145 root - ERROR - Error: Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\mcqgen\StreamlitAPP.py", line 47, in <module>
    text = read_file(uploaded_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Desktop\mcqgen\src\mcqgenerator\utils.py", line 22, in read_file
    raise Exception(
Exception: unsupported file format only pdf and text file suppoted

[2025-01-17 00:39:13,252] 1025 httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-01-17 00:39:31,653] 1025 httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-01-17 00:41:07,171] 1025 httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
